//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Retailer
    {
        public int Retailer_ID { get; set; }
        public string RetailerName { get; set; }
        public int Distributor_ID { get; set; }
        public int Adress_ID { get; set; }
        public string Email { get; set; }
        public int PhoneNumber { get; set; }
        public int MobileNumber { get; set; }
    
        public virtual Adress Adress { get; set; }
        public virtual Distributor Distributor { get; set; }
    }
}
